name: Android

on:
  push:
    branches: verification_github_ci

jobs:
  build_and_test:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: cache
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./ncmb-core/gradlew assembleDebug

    - name: Test with Gradle
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: tasks test --stacktrace
        wrapper-directory: ./ncmb-core
