name: Android

on: [push]

jobs:
  build_and_test:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: ncmb-core
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: .ncmb-core/gradlew build
    - name: Test with Gradle
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: test
